# $FreeBSD$

PORTNAME=	mydb
PORTVERSION=	1.0
CATEGORIES=	devel

MAINTAINER=	koue@chaosophia.net
COMMENT=	Collection of useful functions

LICENSE=	BSD2CLAUSE

USE_GITHUB=	yes
GH_ACCOUNT=	koue
GH_PROJECT=	libmydb

USES=		mysql:103m

CFLAGS+=	-Wall

MAKE_ARGS+=	BINDIR=${PREFIX}/sbin MANDIR=${PREFIX}/man/man

.include <bsd.port.mk>
